parameters:
  host: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.host }}
  pool: ${{ parameters.pool }}
  steps:
  - script: 'npm install -g esy@0.6.7'
    displayName: 'Install esy'
  - script: esy install
    displayName: 'esy install'
  - script: 'esy x which automake'
    displayName: 'Checking binary...'
